Add critic and tidy
jmacdotorg/plerd pull request #46
Opened 2020-06-06 06:46 UTC by vnealv

2020-06-06 06:54 UTC, vnealv commented
Hi @jmacdotorg 

Thanks for the great work you have here, I have finally deployed my blog using Plerd :D 
So as a token of appreciation to your work, I will try to add the enhancement you had in mind of adding perl tidy :D I will also add perl critic along with it. Hope you like it, however I still need to fix a few tests

2020-08-16 21:04 UTC, jmacdotorg requested changes
I'm unfamiliar with Test::Perl::Critic, coming more from a Code::TidyAll background. Is there a simple way to automatically clean up code (e.g. with `tidyall`) that these tests flag?

2020-08-16 21:04 UTC, jmacdotorg commented on META.json
> +            "Test::Perl::Critic" : "0"
Could you please add these to the cpanfile, as well?

2020-08-16 21:04 UTC, jmacdotorg commented on lib/Plerd/Post.pm
> +    my $ret = sort { $a->time_published <=> $b->time_published } values(%{$self->webmentions_by_source});
This changes this method's behavior? It is supposed to return a list (the output of the call to sort()), not a scalar value.

2026-06-21 23:00 UTC, jmacdotorg commented
Closing this as well-intentioned but quite stale now (which is my fault as much as anyone's, as I return my attention to this project). Feel free to re-open as a PR against the current codebase. (My first comment about the cpanfile would remain active, in that case.)

2026-06-21 23:00 UTC, closed without merging